### PR TITLE
Drop support for Ruby 1.8.7 and 1.9.2

### PR DESCRIPTION
**Pull request by jeremyw**

### CODE REVIEW

**Comment by kbrock** [comment]
cool - I guess that answers that

**Comment by kbrock** [comment]
@jeremyw Awh man - ree is 1.8.7

**Comment by jeremyw** [comment]
That's some old shit.

**Comment by kbrock** [comment]
While you're in there, I think you may want to change `rbx` to `rbx-2`. takes a long time for `rbx` to pass travis [[via](http://docs.travis-ci.com/user/languages/ruby/#Supported-Ruby-Versions)]:

    When using Rubinius, there's currently an issue with selecting the correct version in
    RVM in our build environment, but only when specifying rbx as your version. As a
    workaround, specify rbx-2 instead

**Comment by jeremyw** [comment]
OK, I'll update it to rbx-2.

Do you know what's going on with ruby 2.2? I think it's failing because minitest was removed from stdlib. I'm installing 2.2.2 now to test locally.

**Comment by kbrock** [comment]
2.2: see #26

**Comment by kbrock** [comment]
Don't add test unit - you can get away with 100% minitest.
Also, for emitters, do you want those in rspec / minitest / minitest-spec ?

**Comment by kbrock** [comment]
Yea. all the tests passed in ~1 minute for all ruby versions but rbx.
Travis docs say that 3 versions of rbx is pre-installed, but taking that long to build suggests rbx-2 isn't being picked up either.

Maybe you need to specify a longer version? like rbx-2.2.7 ?

**Comment by jeremyw** [comment]
minitest is good with me. I'll get your other fix.

**Pull request merged**
